var ballTypes = [
  {
    name: "white",
    id: 0,
    count: 1,
    price: 10,
    speed: 2,
    speedPrice: 10,
    power: 5,
    powerPrice: 10,
  },
  {
    name: "red",
    id: 1,
    count: 0,
    price: 150,
    speed: 1,
    speedPrice: 100,
    power: 10,
    powerPrice: 100,
  },
  {
    name: "green",
    id: 2,
    count: 0,
    price: 1500,
    speed: 1.25,
    speedPrice: 1000,
    power: 1.5,
    powerPrice: 1000,
  },
  {
    name: "yellow",
    id: 3,
    count: 0,
    price: 10000,
    speed: 1.1,
    speedPrice: 5000,
    power: 0.1,
    powerPrice: 5000,
  },
];
